### ISSUE TITLE
Book suggestion: The Handbook of Research Synthesis and Meta-Analysis by Harris and Cooper(eds.)

### ISSUE THREAD

**Issue by rasmusklokker** [wviechtb/meta_analysis_books#1]
The reason for this suggestion is mainly that i see Raudenbush, 1994 cited almost anywhere that refers to the inner workings of random effects models. While the other chapters may not constitute seminal works, the book gets around most of the process of conducting a meta-analysis. It seems part V-VII would probably be the most relevant chapters for reproducing in R however. 

Much of the content probably overlaps what is covered in the books you've already gone through but there are some chapters covering some more advanced topics as well.

Lastly, thank you for doing this it is really an awesome piece of work and greatly appreciated!!!

**Comment by wviechtb** [comment]
I actually cover the Raudenbush chapter on the metafor package website: http://www.metafor-project.org/doku.php/analyses:raudenbush2009 I'll take another look at the rest of the book (but to keep things current, the 3rd edition) and see what else could be covered. The handbook is of course one of the quintessential textbooks on meta-analysis, so yes, that would be a nice addition.

**Comment by wviechtb** [comment]
Ok, I am working on it. It's a long book, so it might take me a while to finish this. I'll keep pushing updates to the repo as I make progress.

**Comment by rasmusklokker** [comment]
You're a machine!! I'll take a look at Raudenbush in the meantime, thanks for the link! The metafor site is jampacked with good stuff, so I probably overlooked the Raudenbush chapter until now. 
Looking forward to updates!!

**Comment by wviechtb** [comment]
Took a while, but I've finished this.
